yarr/urls.py
from django.conf.urls import url

from . import views
from .constants import ENTRY_READ, ENTRY_SAVED, ENTRY_UNREAD


app_name = "yarr"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^all/$", views.list_entries, name="list_all"),
    url(r"^unread/$", views.list_entries, {"state": ENTRY_UNREAD}, name="list_unread"),
    url(r"^saved/$", views.list_entries, {"state": ENTRY_SAVED}, name="list_saved"),
    # Feed views
    url(r"^all/(?P<feed_pk>\d+)/$", views.list_entries, name="list_all"),
    url(
        r"^unread/(?P<feed_pk>\d+)/$",
        views.list_entries,
        {"state": ENTRY_UNREAD},
        name="list_unread",
    ),
    url(
        r"^saved/(?P<feed_pk>\d+)/$",
        views.list_entries,
        {"state": ENTRY_SAVED},
        name="list_saved",
    ),
    # Feed management
    url(r"^feeds/$", views.feeds, name="feeds"),
    url(r"^feeds/add/$", views.feed_form, name="feed_add"),
    url(r"^feeds/(?P<feed_pk>\d+)/$", views.feed_form, name="feed_edit"),
    url(r"^feeds/(?P<feed_pk>\d+)/delete/$", views.feed_delete, name="feed_delete"),
    url(r"^feeds/export/$", views.feeds_export, name="feeds_export"),
    # Flag management without javascript
    url(
        r"^state/read/all/$",
        views.entry_state,
        {"state": ENTRY_READ, "if_state": ENTRY_UNREAD},
        name="mark_all_read",
    ),
    url(
        r"^state/read/feed/(?P<feed_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_READ},
        name="mark_feed_read",
    ),
    url(
        r"^state/read/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_READ},
        name="mark_read",
    ),
    url(
        r"^state/unread/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_UNREAD},
        name="mark_unread",
    ),
    url(
        r"^state/save/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_SAVED},
        name="mark_saved",
    ),
    #
    # JSON API
    #
    url(r"^api/$", views.api_base, name="api_base"),
    url(r"^api/feed/get/$", views.api_feed_get, name="api_feed_get"),
    url(r"^api/feed/pks/$", views.api_feed_pks_get, name="api_feed_pks_get"),
    url(r"^api/entry/get/$", views.api_entry_get, name="api_entry_get"),
    url(r"^api/entry/set/$", views.api_entry_set, name="api_entry_set"),
]

yarr/templates/yarr/base.html
{% extends "base.html" %}

yarr/templates/yarr/base_all.html
{% extends "yarr/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "yarr/index.css" %}" type="text/css" />
{{ block.super }}
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="yarr {% block page_class %}{% endblock %}">
    <div class="control">
        {% block yarr_control %}{% endblock %}
    </div>

    {% block yarr_body %}
    <div class="body with-sidebar">
            <div class="sidebar">
                {% block yarr_sidebar %}{% endblock %}
            </div>

            <div class="content">
                {% block yarr_content %}{% endblock %}
            </div>
        </div>
    </div>
    {% endblock %}
</div>
{% endblock %}

{% block js %}
<script>YARR_CONFIG={{ yarr_settings.config|safe|default:'{}' }};</script>
<script src="{% static "yarr/index.js" %}"></script>
{{ block.super }}
{% endblock %}

yarr/templates/yarr/base_manage.html
{% extends "yarr/base_all.html" %}

{% block yarr_control %}
<ul class="menu_manage">
    <li>
        <a
            href="{% url "yarr:index" %}"
            class="menu_manage-read_feeds"
        >Read feeds</a>
    </li>
    {% if not feeds %}
        <li>
            <a
                href="{% url "yarr:feeds" %}"
                class="menu_manage-manage_feeds"
            >Manage feeds</a>
        </li>
    {% endif %}
</ul>
{% endblock %}

{% block yarr_body %}
    <div class="body">
        <div class="content">
            {% block yarr_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

yarr/templates/yarr/confirm.html
{% extends "yarr/base_manage.html" %}

{% block yarr_content %}

<form action="." method="POST" class="yarr_confirm">

{% if entry %}
    <h2>{{ entry.title }}</h2>
{% endif %}

<p>{{ message }}</p>

<div>
    {% csrf_token %}
    <input type="submit" value="{{ submit_label }}">
</div>

</form>

{% endblock %}

yarr/templates/yarr/feed_add.html
{% extends "yarr/base_manage.html" %}

{% block yarr_content %}

<div id="yarr_feed_add">
    {{ block.super }}

    {% include "yarr/include/form_feed_add.html" %}
</div>

{% endblock %}

yarr/templates/yarr/feed_edit.html
{% extends "yarr/base_manage.html" %}

{% block yarr_content %}

<div id="yarr_feed_edit">
    {{ block.super }}

    {% include "yarr/include/form_feed_edit.html" %}
</div>

{% endblock %}

yarr/templates/yarr/feeds.html
{% extends "yarr/base_manage.html" %}
{% load static %}

{% block yarr_content %}
<div id="feeds">

<h2>Add feed</h2>
{% include "yarr/include/form_feed_add.html" %}


<h2>Manage feeds</h2>

<table class="feed_manage">

    <colgroup>
        <col class="name">
        <col class="unread">
        <col class="feed_status">
        <col class="next_check">
    </colgroup>

    <thead>
        <tr>
            <th>Feed</th>
            <th>Unread</th>
            <th>Status</th>
            <th>Next check</th>
        </tr>
    </thead>

    <tbody>
    {% for feed in feeds %}
        <tr
            data-yarr-pk="{{ feed.pk }}"
            data-yarr-error="{{ feed.error }}"
            data-yarr-last-checked="{{ feed.last_checked|default:"Not checked yet" }}"
            data-yarr-is-active="{{ feed.is_active|lower }}"
        >
            <td><a href="{% url "yarr:feed_edit" feed_pk=feed.pk %}">{{ feed }}</a></td>

            <td>{{ feed.count_unread }}/{{ feed.count_total }}</td>

            {% if feed.is_active %}
                {% if feed.error %}
                    <td class="status--problem">Problem</td>
                {% else %}
                    <td class="status--active">Active</td>
                {% endif %}
            {% else %}
                <td class="status--inactive">Inactive</td>
            {% endif %}

            {% if feed.is_active %}
                <td>{{ feed.next_check|default:"As soon as possible" }}</td>
            {% else %}
                <td>Never</td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>

<h2>Export feeds</h2>

<p><a href="{% url "yarr:feeds_export" %}" rel="nofollow">Export feeds as OPML</a>

</div>

{% endblock %}

yarr/templates/yarr/list_entries.html
{% extends "yarr/base_all.html" %}
{% load static %}

{% block page_class %}yarr-list-entries{% if not sidebar_default %} yarr__conf-sidebar_override{% endif %}{% if not layout_article %} yarr__conf-layout_list{% endif %}{% endblock %}

{% block yarr_control %}
{% spaceless %}
    <div class="menu">
        <ul class="menu_ctl">
            <li>
                <a
                    href="?sidebar={% if sidebar_default %}{{ constants.SIDEBAR_OVERRIDE }}{% else %}{{ constants.SIDEBAR_DEFAULT }}{% endif %}"
                    class="menu_ctl-sidebar_toggle{% if sidebar_default %} selected{% endif %}"
                ></a>
            </li>
        </ul>

        <div class="menu_state">
            <span class="menu_state-{% if state == constants.ENTRY_UNREAD %}unread{% elif state == constants.ENTRY_SAVED %}saved{% else %}all{% endif %}"></span>
            <ul>
                <li>
                    <a
                        href="{% url 'yarr:list_all' %}"
                        class="menu_state-all{% if state is None %} selected{% endif %}"
                    >All</a>
                </li>
                <li>
                    <a
                        href="{% url 'yarr:list_unread' %}"
                        class="menu_state-unread{% if state == constants.ENTRY_UNREAD %} selected{% endif %}"
                    >Unread</a>
                </li>
                <li>
                    <a
                        href="{% url 'yarr:list_saved' %}"
                        class="menu_state-saved{% if state == constants.ENTRY_SAVED %} selected{% endif %}"
                    >Saved</a>
                </li>
            </ul>
        </div>

        <div class="menu_sort">
            <span class="menu_sort-{% if order_asc %}asc{% else %}desc{% endif %}"></span>
            <ul>
                <li>
                    <a
                        href="?order={{ constants.ORDER_DESC }}"
                        class="menu_sort-desc{% if not order_asc %} selected{% endif %}"
                    >Latest first</a>
                </li>
                <li>
                    <a
                        href="?order={{ constants.ORDER_ASC }}"
                        class="menu_sort-asc{% if order_asc %} selected{% endif %}"
                    >Oldest first</a>
                </li>
            </ul>
        </div>

        <div class="menu_layout">
            <span class="menu_layout-{% if layout_article %}article{% else %}list{% endif %}"></span>
            <ul>
                <li>
                    <a
                        href="?layout={{ constants.LAYOUT_ARTICLE}}"
                        class="menu_layout-article{% if layout_article %} selected{% endif %}"
                    >Article view</a>
                </li>
                <li>
                    <a
                        href="?layout={{ constants.LAYOUT_LIST }}"
                        class="menu_layout-list{% if not layout_article %} selected{% endif %}"
                    >List view</a>
                </li>
            </ul>
        </div>

        <div class="menu_op">
            <span class="menu_op-mark_read"></span>
            <ul>
            {% if feed %}
                <li>
                    <a
                        href="{% url 'yarr:mark_feed_read' feed_pk=feed.pk %}"
                        class="menu_op-mark_read"
                    >Mark feed read</a>
                </li>
            {% else %}
                <li>
                    <a
                        href="{% url 'yarr:mark_all_read' %}"
                        class="menu_op-mark_read"
                    >Mark all read</a>
                </li>
            </ul>
            {% endif %}
        </div>

        <ul class="menu_manage">
            <li>
                <a
                    href="{% url "yarr:feeds" %}"
                    class="menu_manage-manage_feeds"
                ></a>
            </li>
        </ul>

    </div>

{% endspaceless %}
    <div class="feednav">
        {% if entries.paginator.num_pages > 1 %}
            <ul class="paginated">
                {% if pagination.has_previous %}
                    <li><a href="?{{ pagination.previous.query }}" class="paginated-previous">&laquo;</a></li>
                {% endif %}

                {% if pagination.first %}
                    <li><a href="?{{ pagination.first.query }}">{{ pagination.first.number }}</a></li>
                    <li><span>…</span></li>
                {% endif %}

                {% for linkpage in pagination.pages %}
                    {% if linkpage.current %}
                        <li><span class="selected">{{ linkpage.number }}</span></li>
                    {% else %}
                        <li><a href="?{{ linkpage.query }}">{{ linkpage.number }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if pagination.show_last %}
                    <li><span>…</span></li>
                    <li><a href="?{{ pagination.last.query }}">{{ pagination.last.number }}</a></li>
                {% endif %}

                {% if pagination.has_next %}
                    <li><a href="?{{ pagination.next.query }}" class="paginated-next">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

    {# List mode needs a detached radio to close items #}
    {% if not layout_article %}
    <input type="radio" name="layout_list" id="layout_list-0">
    {% endif %}

{% endblock %}


{% block yarr_sidebar %}
<div class="sidebar-body">
    <ul class="feed_menu">
        <li><a href="{% url current_view %}" class="view_all{% if not feed %} disabled{% endif %}">View all feeds</a></li>
    </ul>

    <ul class="feed_list_feeds">
        {% for feed in feeds %}
        <li data-yarr-feed="{{ feed.pk }}" {% if feed.count_unread %}class="feed_unread"{% endif %}>
            <a href="{% url current_view feed_pk=feed.pk %}">{{ feed }}</a><span class="count_unread">{{ feed.count_unread }}</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block yarr_content %}
    {% if entries.object_list|length == 0 %}
        <p>No {% if state == constants.ENTRY_UNREAD %}unread {% endif %}{% if state == constants.ENTRY_SAVED %}saved {% endif %}items</p>

    {% else %}

        {% for entry in entries.object_list %}
            {% include "yarr/include/entry.html" %}
        {% endfor %}

    {% endif %}
{% endblock %}