yarr/urls.py
from django.conf.urls import url

from . import views
from .constants import ENTRY_READ, ENTRY_SAVED, ENTRY_UNREAD


app_name = "yarr"

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^all/$", views.list_entries, name="list_all"),
    url(r"^unread/$", views.list_entries, {"state": ENTRY_UNREAD}, name="list_unread"),
    url(r"^saved/$", views.list_entries, {"state": ENTRY_SAVED}, name="list_saved"),
    # Feed views
    url(r"^all/(?P<feed_pk>\d+)/$", views.list_entries, name="list_all"),
    url(
        r"^unread/(?P<feed_pk>\d+)/$",
        views.list_entries,
        {"state": ENTRY_UNREAD},
        name="list_unread",
    ),
    url(
        r"^saved/(?P<feed_pk>\d+)/$",
        views.list_entries,
        {"state": ENTRY_SAVED},
        name="list_saved",
    ),
    # Feed management
    url(r"^feeds/$", views.feeds, name="feeds"),
    url(r"^feeds/add/$", views.feed_form, name="feed_add"),
    url(r"^feeds/(?P<feed_pk>\d+)/$", views.feed_form, name="feed_edit"),
    url(r"^feeds/(?P<feed_pk>\d+)/delete/$", views.feed_delete, name="feed_delete"),
    url(r"^feeds/export/$", views.feeds_export, name="feeds_export"),
    # Flag management without javascript
    url(
        r"^state/read/all/$",
        views.entry_state,
        {"state": ENTRY_READ, "if_state": ENTRY_UNREAD},
        name="mark_all_read",
    ),
    url(
        r"^state/read/feed/(?P<feed_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_READ},
        name="mark_feed_read",
    ),
    url(
        r"^state/read/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_READ},
        name="mark_read",
    ),
    url(
        r"^state/unread/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_UNREAD},
        name="mark_unread",
    ),
    url(
        r"^state/save/entry/(?P<entry_pk>\d+)/$",
        views.entry_state,
        {"state": ENTRY_SAVED},
        name="mark_saved",
    ),
    #
    # JSON API
    #
    url(r"^api/$", views.api_base, name="api_base"),
    url(r"^api/feed/get/$", views.api_feed_get, name="api_feed_get"),
    url(r"^api/feed/pks/$", views.api_feed_pks_get, name="api_feed_pks_get"),
    url(r"^api/entry/get/$", views.api_entry_get, name="api_entry_get"),
    url(r"^api/entry/set/$", views.api_entry_set, name="api_entry_set"),
]

yarr/templates/yarr/include/entry.html
<div class="entry{% if entry.state == constants.ENTRY_READ %} read{% endif %}{% if entry.state == constants.ENTRY_SAVED %} saved{% endif %}"
    data-yarr-feed="{{ entry.feed.pk }}"
    data-yarr-pk="{{ entry.pk }}"
    data-yarr-state="{{ entry.state }}"
>
    {% if not layout_article %}
    <input type="radio" name="layout_list" id="layout_list-{{ entry.pk }}">
    <label class="summary" for="layout_list-{{ entry.pk }}" aria-hidden="true">
        <span class="feed">{{ entry.feed.title }}</span>
        <span class="title">{{ entry.title|default:"Untitled" }}</span>
        <span class="date">{{ entry.date|date:"M d Y, H:i" }}</span>
    </label>
    <div class="article">
        <label class="summary--close" for="layout_list-0" aria-hidden="true">
        &nbsp;
        </label>
    {% endif %}

    <div class="header">
        <h2>
            {% if entry.url %}<a href="{{ entry.url }}" target="_blank" class="yarr:link">{% endif %}
            {{ entry.title|default:"Untitled" }}
            {% if entry.url %}</a>{% endif %}
        </h2>
        <div class="meta">
            <p class="date">{{ entry.date|date:"M d Y, H:i" }}</p>
            <p class="feed">from
                {% if entry.feed.site_url %}<a href="{{ entry.feed.site_url }}" target="_blank">{% endif %}
                {{ entry.feed.title }}
                {% if entry.feed.site_url %}</a>{% endif %}
                {% if entry.author %}by <span class="author">{{ entry.author }}</span>{% endif %}
            </p>
        </div>
    </div>

    <div class="content">
        {{ entry.content|safe }}

        {% if entry.tags %}<p class="tags">{{ entry.tags }}</p>{% endif %}
        {% if entry.comments_url %}<p class="comments"><a href="{{ entry.comments_url }}" target="_blank">Comments</a></p>{% endif %}
    </div>

    <div class="control">
        <ul>
        {% if entry.state == constants.ENTRY_READ %}
            <li><a href="{% url 'yarr:mark_unread' entry_pk=entry.pk %}">Mark as unread</a></li>
            <li><a href="{% url 'yarr:mark_saved' entry_pk=entry.pk %}">Save</a></li>
        {% else %}
            {% if entry.state == constants.ENTRY_SAVED %}
                <li><a href="{% url 'yarr:mark_read' entry_pk=entry.pk %}">Discard as read</a></li>
                <li>Saved</li>
            {% else %}
                <li><a href="{% url 'yarr:mark_read' entry_pk=entry.pk %}">Mark as read</a></li>
                <li><a href="{% url 'yarr:mark_saved' entry_pk=entry.pk %}">Save</a></li>
            {% endif %}
        {% endif %}
        </ul>
    </div>

    {% if not layout_article %}
    </div>
    {% endif %}

</div>

yarr/templates/yarr/include/form_feed_add.html
<form action="{% url "yarr:feed_add" %}" method="POST" class="feed_form" id="yarr_feed_add">
{% csrf_token %}

<table>
{{ feed_form.as_table }}
<tr><td></td><td><input type="submit" value="Add feed" /></td></tr>
</table>

</form>

yarr/templates/yarr/include/form_feed_edit.html
{% if feed.error %}
    <h2>Problem with feed</h2>
    <p>Last time it was checked, the feed had the following error:</p>
    <blockquote><pre><code>{{ feed.error }}</code></pre></blockquote>

    {% if feed.is_active %}
        <p>The feed is still being checked.</p>
    {% else %}
        <p>The feed is no longer being checked.</p>
    {% endif %}

    <h2>Edit feed</h2>
{% endif %}

<form action="{% url "yarr:feed_edit" feed_pk=feed.pk %}" method="POST" class="feed_form">
{% csrf_token %}

<table>
<tr class="required"><th>Title:</th><td>{{ feed.title }}</td></tr>
<tr><td>Last check:</td><td>{{ feed.last_checked|default:"Not checked yet" }}</td></tr>
<tr><td>Next check:</td><td>{{ feed.next_check|default:"As soon as possible" }}</td></tr>
<tr><td>Last updated:</td><td>{{ feed.last_updated|default:"Not checked yet" }}</td></tr>
{{ feed_form.as_table }}
<tr>
  <td></td>
  <td>
    <input type="submit" value="Save changes">
    <a href="{% url "yarr:feed_delete" feed_pk=feed.pk %}">Delete this feed</a>
  </td>
</tr>
</table>

</form>